export const  featureDictionary = 
[{
  feature :  "Metal Legs",
    synonyms: [
        "steel legs",
        "aluminum supports",
        "iron base",
        "metallic feet",
        "chrome legs",
        "brass legs",
        "stainless steel legs",
        "industrial legs",
        "bronze legs",
        "metal supports",
        "metal pedestals",
        "contemporary metal legs",
        "metal stilts",
        "aluminum frame legs",
        "metal rod legs",
        "brushed metal legs",
        "iron feet",
        "metal tube legs",
        "metal hairpin legs",
        "steel base",
        "metal framework legs",
        "metallic support structure",
        "metal spindle legs",
        "alloy legs",
        "metal foundation"
    ],
    spelling_variations: [
        "metal leg",
        "metl legs",
        "mettal legs",
        "metal leggs",
        "matal legs",
        "metal lags",
        "steel legs",
        "metal-legs",
        "medal legs",
        "metel legs",
        "metol legs",
        "metil legs",
        "metalic legs",
        "metallegs",
        "metal leg's"
    ]
},
{
    feature: "Continuous Structure",
    synonyms: [
        "single-piece design",
        "seamless structure",
        "uninterrupted frame",
        "all-in-one construction",
        "unified body",
        "flowing form",
        "one-piece design",
        "integrated frame",
        "solid structure",
        "contiguous form",
        "seamless body",
        "monolithic structure",
        "unbroken frame",
        "cohesive design",
        "uniform structure",
        "connected elements",
        "joined construction",
        "integral design",
        "unified framework",
        "unsegmented structure",
        "uninterrupted silhouette",
        "fused components",
        "non-sectional design",
        "streamlined structure",
        "harmonious frame"
    ],
    spelling_variations: [
        "continous structure",
        "continuos structure",
        "continuous struture",
        "continuouse structure",
        "continuus structure",
        "contiguous structure",
        "continuous-structure",
        "continuous structur",
        "continu structure",
        "continuous stucture",
        "continuousstructure",
        "continuos structur",
        "continuous-structur",
        "continue structure",
        "continuius structure"
    ]
},
{
      feature: "With Armrest",
    synonyms: [
        "arm support",
        "side rests",
        "arm guards",
        "elbow rests",
        "side supports",
        "arm platforms",
        "armrests included",
        "hand rests",
        "armrest equipped",
        "arm braces",
        "forearm rests",
        "arm holders",
        "side arms",
        "arm pads",
        "limb supports",
        "sided support",
        "arm cushions",
        "lateral supports",
        "armed design",
        "arm flanks",
        "comfort arms",
        "arm panels",
        "side extensions",
        "arm barriers",
        "limb rests"
    ],
    spelling_variations: [
        "with arm rest",
        "with arm-rest",
        "witharmrest",
        "with-armrest",
        "with armrets",
        "with armrests",
        "w armrest",
        "w/ armrest",
        "with arm res",
        "with armrestt",
        "with armrast",
        "has armrest",
        "includes armrest",
        "armrest included"
    ]
},
{
      feature: "Squared Arms",
    synonyms: [
        "rectangular arms",
        "right-angled arms",
        "boxy arms",
        "geometric arms",
        "angular arms",
        "straight arms",
        "square-edged arms",
        "block arms",
        "cubic arms",
        "sharp-cornered arms",
        "linear arms",
        "regular arms",
        "box-shaped arms",
        "right-angle supports",
        "flat-top arms",
        "orthogonal arms",
        "quadrilateral arms",
        "rigid arms",
        "perpendicular arms",
        "rectilinear arms",
        "crisp arms",
        "hard-edged arms",
        "cornered arms",
        "clean-lined arms",
        "structured arms"
    ],
    spelling_variations: [
        "square arms",
        "squared arm",
        "squarred arms",
        "squard arms",
        "sqared arms",
        "squared-arms",
        "square-arms",
        "squere arms",
        "squired arms",
        "sqrd arms",
        "sqaured arms",
        "squaredarms",
        "squared armes",
        "square armrest",
        "squared armrest"
    ]
},
{
      feature: "roundedArms",
    synonyms: [
        "curved arms",
        "circular arms",
        "smooth arms",
        "contoured arms",
        "arched arms",
        "soft-edged arms",
        "curved armrests",
        "rounded support",
        "crescent arms",
        "dome-shaped arms",
        "bulbous arms",
        "sculpted arms",
        "oval arms",
        "round-top arms",
        "curvaceous arms",
        "flowing arms",
        "smoothly contoured arms",
        "semi-circular arms",
        "gentle curve arms",
        "roll arms",
        "cylindrical arms",
        "spherical arms",
        "fluid-shaped arms",
        "arc-shaped arms",
        "undulating arms"
    ],
    spelling_variations: [
        "rounded arms",
        "rounded-arms",
        "rounded arm",
        "round arms",
        "roundedarm",
        "round-arms",
        "rouded arms",
        "roundd arms",
        "rawnded arms",
        "rounded armes",
        "roundedarmrest",
        "rounded armrest",
        "round-shaped arms",
        "rounded-shape arms",
        "runded arms"
    ]
},
{
      feature: "upholstered base",
    synonyms: [
        "padded base",
        "fabric covered base",
        "cushioned foundation",
        "soft base",
        "textile covered bottom",
        "upholstered platform",
        "padded bottom",
        "fabric base",
        "textile foundation",
        "soft bottom structure",
        "cushioned underside",
        "fabric wrapped base",
        "material covered foundation",
        "textile encased base",
        "lined base",
        "padded plinth",
        "upholstered support",
        "covered base",
        "fabric supported bottom",
        "padded foundation",
        "textile clad base",
        "material adorned platform",
        "cushioned plinth",
        "upholstered underbelly",
        "soft foundation"
    ],
    spelling_variations: [
        "upholstered-base",
        "upholsterd base",
        "upholstered bace",
        "upolstered base",
        "upholstered-bace",
        "upholsteredbase",
        "upholstered bas",
        "uphostered base",
        "upholstered baes",
        "upholstere base",
        "upfolstered base",
        "upholestered base",
        "upholstred base",
        "upholstered basis",
        "upholstered bottom"
    ]
},
{
      feature: "Wooden plinth",
    synonyms: [
        "timber base",
        "wooden foundation",
        "wood platform",
        "wooden pedestal",
        "hardwood plinth",
        "timber stand",
        "wooden support base",
        "solid wood base",
        "wooden underbody",
        "timber foundation",
        "wooden block base",
        "natural wood base",
        "wooden underside",
        "timber pedestal",
        "wood framework base",
        "wooden footing",
        "timber platform",
        "wooden substructure",
        "wood pediment",
        "timber mounting",
        "wooden podium",
        "natural timber base",
        "wood slab base",
        "wooden foundation block",
        "timber support structure"
    ],
    spelling_variations: [
        "wooden-plinth",
        "wooden plynth",
        "wooden plith",
        "wooded plinth",
        "wooden plint",
        "wooden-plint",
        "woodenplinth",
        "wooden plinthe",
        "wood plinth",
        "wooden planth",
        "wooden plimth",
        "woden plinth",
        "wooden plynthe",
        "woonden plinth"
    ]
},
{
      feature: "Fixed Arms",
    synonyms: [
        "stationary arms",
        "immovable arms",
        "permanent arms",
        "non-adjustable arms",
        "static arms",
        "anchored arms",
        "secured arms",
        "rigid arms",
        "non-removable arms",
        "stable arms",
        "fixed armrests",
        "integrated arms",
        "attached arms",
        "non-detachable arms",
        "built-in arms",
        "solid arms",
        "permanent armrests",
        "unmovable arms",
        "set arms",
        "fixed side supports",
        "immobile arms",
        "non-moving arms",
        "welded arms",
        "locked arms",
        "stationary armrests"
    ],
    spelling_variations: [
        "fixed-arms",
        "fixed arm",
        "fixd arms",
        "fixxed arms",
        "fixed-arm",
        "fixedarms",
        "fix arms",
        "fixed armes",
        "fixet arms",
        "fixed arns",
        "fixed armrests",
        "fixed armrest",
        "non-movable arms",
        "firm arms"
    ]
},
{
      feature: "Chesterfield",
    synonyms: [
        "button-tufted sofa",
        "deep buttoned sofa",
        "rolled arm sofa",
        "quilted leather sofa",
        "classic tufted couch",
        "traditional buttoned sofa",
        "leather tufted settee",
        "diamond quilted sofa",
        "luxurious buttoned couch",
        "rolled arm tufted sofa",
        "Victorian tufted sofa",
        "classic English sofa",
        "button-back sofa",
        "capitonné sofa",
        "deep buttoned upholstery",
        "gentlemen's club sofa",
        "traditional English couch",
        "scroll arm tufted sofa",
        "leather quilted couch",
        "deep-set button sofa",
        "diamond pattern tufted sofa",
        "formal buttoned sofa",
        "heritage tufted design",
        "classic buttoned chesterfield",
        "studded leather sofa"
    ],
    spelling_variations: [
        "chester field",
        "chester-field",
        "chesterfeild",
        "chesterfild",
        "chesturfield",
        "chesterfeeld",
        "chesterfeild sofa",
        "chester field sofa",
        "chesterfld",
        "cesterfield",
        "chestfield",
        "chesterfieldsofa",
        "chesterfield-sofa",
        "chesyerfield",
        "chesterfeld"
    ]
},
{
      feature: "Horizontal Tufting",
    synonyms: [
        "lateral button quilting",
        "sideways diamond stitching",
        "crosswise tufting",
        "transverse buttoning",
        "parallel tufted lines",
        "linear button patterning",
        "row tufting",
        "widthwise stitched pattern",
        "side-to-side quilting",
        "horizontal button detail",
        "lateral channel stitching",
        "cross tufting",
        "transverse quilting",
        "horizontal button quilting",
        "sideways capitonné",
        "linear quilted pattern",
        "across stitching",
        "lateral diamond pattern",
        "breadthwise tufting",
        "horizontal stitch detail",
        "crosswise buttoned pattern",
        "lateral quilted lines",
        "parallel button detail",
        "side-to-side tufted pattern",
        "horizontal channel stitching"
    ],
    spelling_variations: [
        "horizontal-tufting",
        "horinzontal tufting",
        "horizontal tuffting",
        "horizontal tufing",
        "horizontle tufting",
        "horizontal-tufing",
        "horizontaltufting",
        "horizonatal tufting",
        "horizontal tuftng",
        "horrizontal tufting",
        "horizontal tutfing",
        "lateral tufting",
        "crossways tufting",
        "horizontal quitting",
        "horizontal button pattern"
    ]
},
{
      feature: "Rectangular Arms",
    synonyms: [
        "box-style arms",
        "straight-profile arms",
        "right-angled arms",
        "angular arms",
        "flat-panel arms",
        "block arms",
        "rectilinear armrests",
        "angular-profile arms",
        "square-sided arms",
        "panel arms",
        "flat-front arms",
        "tile arms",
        "grid arms",
        "slab arms",
        "frame arms",
        "geometric arms",
        "edge arms",
        "straight-edge arms",
        "paneled arms",
        "modular arms",
        "slotted arms",
        "planar arms",
        "slab-profile arms",
        "box-edged arms",
        "panel-profile arms"
    ],
    spelling_variations: [
        "rectangulararms",
        "rectang ular arms",
        "rectangular arms ",
        "rectangluar arms",
        "rectanglar arms",
        "rectangle arms",
        "rectangular-arm",
        "rectanglular arms",
        "rectangular armss",
        "rectangular arm s"
    ]
},
{
      feature: "Plain Back without division",
    synonyms: [
        "solid back",
        "undivided back",
        "smooth backrest",
        "one-piece back",
        "flat back",
        "continuous back",
        "seamless backrest",
        "unbroken back",
        "plain backrest",
        "unsegmented back",
        "single-panel back",
        "uniform back",
        "straight backrest",
        "monolithic back",
        "clean-back design",
        "minimalist back",
        "solid-panel back",
        "one-piece backrest",
        "flat-panel back",
        "solid back support",
        "full backrest",
        "undivided backrest",
        "plain panel back",
        "uninterrupted back",
        "slick back"
    ],
    spelling_variations: [
        "plain backwithout division",
        "plainback without division",
        "plain back withoutdivision",
        "plain back without division ",
        "plain-back without division",
        "plain back without divison",
        "plain backwith out division",
        "plain-back withoutdivision",
        "plainbackwithout division",
        "plain backwithout division"
    ]
},
{
      feature: "Low Back",
       synonyms: [
        "mid-height back",
        "short backrest",
        "low-profile back",
        "low-rise back",
        "reduced back height",
        "compact back",
        "subtle backrest",
        "low-slung back",
        "minimal back",
        "shallow backrest",
        "low-shell back",
        "short-profile back",
        "low-backrest design",
        "low-tier back",
        "lowline back",
        "low-rise backrest",
        "lowback seating",
        "low-support back",
        "low-back frame",
        "dwarf back",
        "grounded back",
        "low-level back",
        "truncated backrest",
        "short-form back",
        "stubby back"
    ],
    spelling_variations: [
        "lowback",
        "low-back ",
        "low bak",
        "lo wback",
        "low bacl",
        "low back ",
        "low-bak",
        "low bck",
        "lowb ack",
        "lowb ack "
    ]
},
{
      feature: "Piping on Back",
    synonyms: [
        "back piping",
        "edged back trim",
        "back piping detail",
        "piped backrest",
        "back seam piping",
        "contrast back piping",
        "back edge piping",
        "piping trim on back",
        "back border piping",
        "outline piping back",
        "back seam trim",
        "back piping accent",
        "back welt trim",
        "welded piping back",
        "back welted edge",
        "piped seam back",
        "back cushion piping",
        "back piping line",
        "piped edge backrest",
        "back trim piping",
        "back piping finish",
        "back welt detail",
        "back panel piping",
        "back piping outline"
    ],
    spelling_variations: [
        "pipingonback",
        "piping onback",
        "piping on back ",
        "pipping on back",
        "piping-on-back",
        "pipng on back",
        "piping on bakc",
        "pipingon back",
        "piiping on back",
        "piping on bck"
    ]
},
{
      feature: "Grid Tufted Back",
    synonyms: [
        "square tufted back",
        "paneled tuft back",
        "crisscross back",
        "checker tuft back",
        "quadrant tufting",
        "box tufted back",
        "grid-pattern tufting",
        "matrix tufted back",
        "grid-quilt back",
        "cubic tufted back",
        "panel tufted back",
        "grid-style tufting",
        "block tufted back",
        "grid-knit tufting",
        "grid quilting back",
        "square-channel tufting",
        "check tuft back",
        "grid-backed tuft",
        "paneled quilting",
        "checkerboard tufting",
        "gridset tufting",
        "square-grid tuft back",
        "tri-grid tufted back",
        "gridline tuft back",
        "grid tuft panel"
    ],
    spelling_variations: [
        "gridtuftedback",
        "grid tuftedback",
        "grid tufted back ",
        "grid-tufted back",
        "grid tufted bakc",
        "grd tufted back",
        "gridtufted back",
        "grid tufted bac",
        "giird tufted back",
        "grid tuftet back"
    ]
},
{
      feature: "Flared arms",
    synonyms: [
        "splayed arms",
        "winged arms",
        "flared-profile arms",
        "bell arms",
        "trumpet arms",
        "flounce arms",
        "outward arms",
        "flare arms",
        "flared-edge arms",
        "flange arms",
        "flair arms",
        "everted arms",
        "flared-side arms",
        "flared-cut arms",
        "wingback arms",
        "flared-armrests",
        "fluted arms",
        "fluted-profile arms",
        "fluted-edge arms",
        "flared-shell arms",
        "flared-form arms",
        "flared-frame arms",
        "wide-flare arms",
        "flared-bracket arms"
    ],
    spelling_variations: [
        "flaredarms",
        "flared arms ",
        "flared-arm s",
        "flareed arms",
        "flared-arms",
        "flarred arms",
        "flared arns",
        "flared armss",
        "flard arms",
        "flaerd arms"
    ]
},
{
      feature: "Fabric",
    synonyms: [
        "textile",
        "cloth",
        "woven material",
        "upholstery fabric",
        "cover material",
        "fabrication",
        "drapery",
        "woven cloth",
        "textile cover",
        "covering fabric",
        "fabric weave",
        "fabric material",
        "upholstery cloth",
        "soft textile",
        "lining fabric",
        "fabric covering",
        "twill",
        "velvet",
        "chenille",
        "microfiber",
        "leatherette",
        "suede",
        "canvas",
        "jacquard",
        "felt",
        "mesh",
        "faux leather"
    ],
    spelling_variations: [
        "fabic",
        "fabric ",
        "fabr ic",
        "fabirc",
        "fabrci",
        "fabrick",
        "fabricc",
        "fabric-",
        "fabrik"
    ]
},
{
      feature: "Flat Arms",
    synonyms: [
        "slab arms",
        "panel arms",
        "flat-profile arms",
        "planar arms",
        "slab-profile armrests",
        "flat-panel arms",
        "board arms",
        "plank arms",
        "flat-edge arms",
        "sheet arms",
        "flat-top arms",
        "flat-surface arms",
        "tray arms",
        "flat-section arms",
        "panel-cut arms",
        "flat slab arms",
        "flatboard arms",
        "panel-profile arms",
        "flat-form arms",
        "flatplane arms",
        "flatrest arms",
        "slabrest arms",
        "flat-module arms",
        "flatblock arms",
        "flatbeam arms"
    ],
    spelling_variations: [
        "flatarms",
        "flat arms ",
        "flat-armss",
        "flta arms",
        "flat arms-",
        "flat armss",
        "flat-arms",
        "flat arm",
        "flat amrs",
        "flat arns"
    ]
},
{
      feature: "Bean",
    synonyms: [
        "bean bag",
        "bean-shaped cushion",
        "bean ottoman",
        "bean pouf",
        "bean seating",
        "bean pod",
        "bean-style seat",
        "bean pillow",
        "bean-form cushion",
        "bean module",
        "bean furniture",
        "bean rest",
        "bean chair",
        "bean lounger",
        "bean stool",
        "bean cushion",
        "bean sack seat",
        "bean pad",
        "bean pouch",
        "bean block",
        "bean block seat",
        "bean foam seat",
        "bean case",
        "bean shell",
        "bean unit"
    ],
    spelling_variations: [
        "bean ",
        "beanbag",
        "bean-bag",
        "ben",
        "beanb ag",
        "beean",
        "bn",
        "beans",
        "bea n",
        "bean  "
    ]
},
{
      feature: "Split Seat",
    synonyms: [
        "dual-seat cushion",
        "divided seat",
        "split-cushion seat",
        "bilevel seat",
        "two-part seat",
        "segmented seat",
        "split-cushion",
        "paired seat",
        "twin-seat cushion",
        "split-pad seat",
        "split bench",
        "split-pad cushion",
        "bisected seat",
        "double-cushion seat",
        "two-piece seat",
        "split foam seat",
        "split upholstered seat",
        "split-seat design",
        "dual-cushion seat",
        "saddle seat",
        "split-surface seat",
        "divided cushion",
        "split-rest seat",
        "two-section seat",
        "split-panel seat"
    ],
    spelling_variations: [
        "splitseat",
        "split seat ",
        "split-seat",
        "spllit seat",
        "splt seat",
        "spilt seat",
        "splitse at",
        "split seatt",
        "spiltseat",
        "split  seat"
    ]
},
{
      feature: "Braid Piping",
    synonyms: [
        "braided trim",
        "corded piping",
        "rope-edge trim",
        "braid welt",
        "braided welt",
        "cord welting",
        "rope piping",
        "braid edge accent",
        "braided border trim",
        "corded welt",
        "twisted piping",
        "plaited piping",
        "braid detailing",
        "rope-edge piping",
        "braid seam finish",
        "braided seam piping",
        "cord edge trim",
        "rope welt detail",
        "braided cushion piping",
        "corded edge piping",
        "braid welt accent",
        "twisted cord trim",
        "braided join trim",
        "rope join piping",
        "plaited seam trim",
        "braided piping accent"
    ],
    spelling_variations: [
        "braidpiping",
        "braid piping ",
        "braide piping",
        "braid-piping",
        "braid pipng",
        "braidpip ing",
        "braidp iping",
        "braied piping",
        "braid piiping",
        "braid pipingg",
        "braid pipong",
        "braidpipng"
    ]
},
{
      feature: "Non-Uniform Seat Division",
    synonyms: [
        "irregular seat segmentation",
        "uneven cushion split",
        "asymmetrical seat division",
        "random seat panels",
        "staggered seat sections",
        "offset cushion divisions",
        "inconsistent seat split",
        "multi-size seat panels",
        "varied seat modules",
        "non-symmetrical seat blocks",
        "unequal seat segments",
        "patchwork seat design",
        "asym seat layout",
        "jigsaw seat pattern",
        "mixed-size seat divisions",
        "broken-line seat split",
        "ragged seat segmentation",
        "interrupted seat division",
        "nonlinear seat panels",
        "uneven bench split",
        "asymmetric cushion segmentation",
        "off-kilter seat split",
        "erratic seat division",
        "randomized seat sections",
        "unequal panel seating"
    ],
    spelling_variations: [
        "nonuniform seat division",
        "non-uniform seat division ",
        "non uniform seat division",
        "nonuniformseat division",
        "non uniformseat division",
        "non-uniformseat division",
        "nonuniform seatdivision",
        "nonuniform-seat division",
        "non unform seat division",
        "non-uniform-seat division",
        "non uniform seatdivision",
        "nonuniformseatdivision",
        "non-uniformseatdivision",
        "non uniform-seat division",
        "nonuniform seat dividion"
    ]
},
{
      feature: "Metal Wire Frame",
    synonyms: [
        "wireframe structure",
        "metal rod frame",
        "wire-supported frame",
        "rod-wire chassis",
        "metal grid frame",
        "wire mesh frame",
        "metal wire chassis",
        "wire skeleton",
        "wire armature",
        "rod-and-wire frame",
        "wire cage frame",
        "metal strand frame",
        "wire grid support",
        "rod frame network",
        "wire bracing frame",
        "metal filament frame",
        "wire lattice frame",
        "tubular wire frame",
        "wire structural frame",
        "metal wire support",
        "wire armature frame",
        "wireframe base",
        "rod-wire support",
        "metal wire network",
        "wire chassis frame",
        "wirework frame"
    ],
    spelling_variations: [
        "metalwire frame",
        "metal wireframe",
        "metal wire frame ",
        "metal-wire frame",
        "metal wirefrme",
        "metal wir frame",
        "metal wire frme",
        "metal wirerr frame",
        "metal wirefr ame",
        "metal wire frm",
        "metal wirr frame",
        "metal wire fr ame",
        "metalwired frame",
        "metel wire frame"
    ]
},
{
      feature: "Curved",
    synonyms: [
        "arched",
        "bowed",
        "arched-profile",
        "radius",
        "arc-shaped",
        "swept-back",
        "elliptical",
        "crescent",
        "convex",
        "concave",
        "flexed",
        "c-shaped",
        "sinuous",
        "rounded-form",
        "undulating",
        "wave-like",
        "fluid profile",
        "curvature",
        "arched silhouette",
        "arched contour",
        "curvilinear",
        "bent",
        "looped",
        "arched-frame",
        "curved-edge",
        "organic curve"
    ],
    spelling_variations: [
        "curved ",
        "curvd",
        "curvedd",
        "crved",
        "curved-",
        "cruved",
        "curv ed",
        "curvede",
        "curveddd",
        "curved–",
        "cur ve d",
        "curvde"
    ]
},
{
      feature: "Upholstered Shell",
    synonyms: [
        "padded shell",
        "cushioned shell",
        "fabric-clad shell",
        "upholstery shell",
        "softshell frame",
        "upholstered body",
        "padded frame shell",
        "cushioned housing",
        "upholstered casing",
        "padded enclosure",
        "textile shell",
        "quilted shell",
        "padded carcass",
        "upholstered cover",
        "fabric shell",
        "cushioned frame",
        "upholstered chassis",
        "soft-shell upholstery",
        "padded shell housing",
        "upholstered shell structure",
        "cushioned shell frame",
        "upholstered framework",
        "padded cover shell",
        "fabric-clad housing",
        "textile-clad shell"
    ],
    spelling_variations: [
        "upholsteredshell",
        "upholstered shell ",
        "upholsterd shell",
        "upholstered–shell",
        "upholsteredsh ell",
        "upholsteredshlel",
        "upholstered shel",
        "upholstered sheel",
        "uph olstered shell",
        "upholstered she ll",
        "upholsteredhshell",
        "upholstered shells",
        "uphoolstered shell"
    ]
},
{
      feature: "Armrest Height Aligned with Backrest",
    synonyms: [
        "arm level with back",
        "flush armrest",
        "armrest-backrest flush",
        "arm-back alignment",
        "arms even with back",
        "armrest levelback",
        "aligned armrests",
        "arm-backrest level",
        "armrest flush to back",
        "armrest-backrest level",
        "arms inline with back",
        "arm-back flush design",
        "level armrest",
        "arm-backrest alignment",
        "arm’s height flush back",
        "armrest matched back height",
        "armrest and back aligned",
        "armrest-backrest parallel",
        "backrest-armrest level",
        "armrest at back height",
        "arm-backrest coordination",
        "armrest even-back",
        "aligned arm and backrest",
        "arm-backrest sync",
        "armrest-back sync"
    ],
    spelling_variations: [
        "armrestheight aligned with backrest",
        "armrest heightaligned with backrest",
        "armrest height alignedwith backrest",
        "armrest height aligned withbackrest",
        "armrest height aligned with backrest ",
        "armrest-height aligned with backrest",
        "armrest height-aligned with backrest",
        "armrest height alignedwithbackrest",
        "armrestheightaligned with backrest",
        "armrest height alignedwith backrest",
        "armrest heightalignedwith backrest",
        "armrest height aligned withback rest",
        "armrestheight alignedwithbackrest",
        "armrest heightaligned withbackrest",
        "armrest height alignedwith back rest"
    ]
},
{
      feature: "Leather Back Covering",
    synonyms: [
        "leather-wrapped back",
        "leather-clad backrest",
        "back leather upholstery",
        "leather-backed rest",
        "back covered in leather",
        "leather panel back",
        "full leather back",
        "leather sheathed backrest",
        "backrest in leather",
        "leather finish back",
        "leather-lined back",
        "leather back panel",
        "back leather casing",
        "leather-clad support",
        "leather back cover",
        "backrest leather sheath",
        "leather skinned back",
        "leather back overlay",
        "leatherback design",
        "back leather wrap",
        "leather rear panel",
        "rear leather backrest",
        "smooth leather back",
        "premium leather back",
        "leather-draped back"
    ],
    spelling_variations: [
        "leatherback covering",
        "leather backcovering",
        "leather back covering ",
        "leather-back covering",
        "leather bak covering",
        "leather back coverng",
        "lether back covering",
        "leather bac covering",
        "leatherbackcovering",
        "leather back coverin",
        "leather backcover ing",
        "leather backcovering ",
        "leather back coering",
        "leather back coveringg",
        "leatherbcak covering"
    ]
},
{
      feature: "Rounded Arms",
    synonyms: [
        "curved armrests",
        "circular-profile arms",
        "oval arms",
        "arched arms",
        "bulbous arms",
        "tubular arms",
        "pillowed arms",
        "barrel arms",
        "radius-edge arms",
        "looped arms",
        "semicircular arms",
        "arch-profile arms",
        "egg-shaped arms",
        "contoured arms",
        "soft-radius arms",
        "round-top arms",
        "smooth-curve arms",
        "pod arms",
        "curve-edge arms",
        "bulging arms",
        "rounded-edge arms",
        "reclined curve arms",
        "bean-shaped arms",
        "arched-edge arms",
        "rounded-shell arms"
    ],
    spelling_variations: [
        "rounded arms ",
        "rounded-arms",
        "roundedarm s",
        "roundd arms",
        "rounded armss",
        "rounded arns",
        "rounded ar m s",
        "rounded-amrs",
        "roundedarms",
        "rounded ar nz",
        "roundedar ms",
        "rounded  arms",
        "rounded–arms",
        "rounde d arms",
        "rounded arm"
    ]
},
{
      feature: "Sinuous Curve Arms",
    synonyms: [
        "wavy arms",
        "s-shaped arms",
        "undulating armrests",
        "flowing curve arms",
        "sinuous-profile arms",
        "ribbon-like arms",
        "meandering arms",
        "serpentine arms",
        "s-curve arms",
        "swooping arms",
        "snake-line arms",
        "ripple arms",
        "wave-form arms",
        "curvy arms",
        "sinusoidal arms",
        "sweeping curve arms",
        "squiggle arms",
        "ribbon-profile arms",
        "sinuous-edge arms",
        "meander arms",
        "twist curve arms",
        "flow-line arms",
        "graceful curve arms",
        "flowing-profile arms",
        "undulate arms"
    ],
    spelling_variations: [
        "sinuouscurve arms",
        "sinuous curvearms",
        "sinuous curve arms ",
        "sinuous-curve arms",
        "sinuous curve armss",
        "sinuos curve arms",
        "sinous curve arms",
        "sinuous curve arm s",
        "sinouscurve arms",
        "sinuouscurvature arms",
        "sinuous curve ar ns",
        "snuous curve arms",
        "sinuos-cur ve arms",
        "sinuous curve armz",
        "sinuouscurvearms"
    ]
},
{
      feature: "Mid Back",
    synonyms: [
        "medium-height backrest",
        "mid-height back",
        "mid-profile back",
        "mid-rise backrest",
        "moderate back height",
        "average backrest",
        "midline back",
        "mid-tier back",
        "mid-back support",
        "midlevel backrest",
        "intermediate back",
        "midrise back",
        "mid-level backrest",
        "midway backrest",
        "mid back frame",
        "mid-back design",
        "mid-height support",
        "mid-stack backrest",
        "mid-section back",
        "mid-backrest height",
        "mid-profile support",
        "midback seating",
        "mid-shell back",
        "midback frame",
        "midback panel"
    ],
    spelling_variations: [
        "midback",
        "mid back ",
        "mid-back",
        "midbak",
        "midb ack",
        "mid-bak",
        "midbaxk",
        "md-back",
        "mid-backk",
        "mib back",
        "mid bac k",
        "midbck"
    ]
},
{
      feature: "Cylindrical Back",
    synonyms: [
        "round backrest",
        "barrel back",
        "tube-shaped back",
        "tube backrest",
        "drum back",
        "roller back",
        "circular-profile back",
        "column back",
        "pipe backrest",
        "cylinder back"
    ],
    spelling_variations: [
        "cylindricalback",
        "cylindrical back ",
        "cylindrical-back",
        "cylindrical bak",
        "cilindrical back",
        "cylndr cal back",
        "cylindrcal back",
        "cylindrical bac",
        "cylindrical bacl"
    ]
},
{
      feature: "Organic Shape",
    synonyms: [
        "natural form",
        "fluid shape",
        "curvilinear form",
        "biomorphic shape",
        "freeform contour",
        "naturalistic silhouette",
        "flowing shape",
        "biomorphic curve",
        "undulating form",
        "organic contour"
    ],
    spelling_variations: [
        "organicshape",
        "organic shape ",
        "organic-shape",
        "orgnic shape",
        "organinc shape",
        "organic shap",
        "organic shap e",
        "organi cshape"
    ]
},
{
      feature: "Armrest integrated with Structure",
    synonyms: [
        "built-in armrests",
        "structural arm support",
        "armrests as frame",
        "integral arms",
        "frame-integrated arms",
        "one-piece arms",
        "arm-frame fusion",
        "monolithic arms",
        "armrest-frame merge",
        "armrest-struct fusion"
    ],
    spelling_variations: [
        "armrestintegrated with structure",
        "armrest integratedwith structure",
        "armrest integrated withstructure",
        "armrest integrated with structure ",
        "armrest-integrated with structure",
        "armrest integrated-with structure",
        "armrest integrated with structure"
    ]
},
{
      feature: "Sinuous",
    synonyms: [
        "wavy",
        "undulating",
        "curvy",
        "serpentine",
        "flowing",
        "meandering",
        "ribbon-like",
        "s-shaped",
        "sweeping",
        "gracefully curved"
    ],
    spelling_variations: [
        "sinuous ",
        "sinuos",
        "snuous",
        "sinous",
        "sinu ous",
        "sinous-",
        "sinuouss",
        "sinuou s"
    ]
},
{
      feature: "Metal plinth",
    synonyms: [
        "metal base",
        "steel plinth",
        "metal pedestal",
        "metal platform",
        "metal footing",
        "iron plinth",
        "aluminum plinth",
        "metal dais",
        "metal riser",
        "metal sub-base"
    ],
    spelling_variations: [
        "metalplinth",
        "metal plinth ",
        "metal-plinth",
        "metel plinth",
        "metal plinthh",
        "metal plint",
        "metalplint",
        "metalplinth "
    ]
},
{
      feature: "WithOptionalLooseCushions",
    synonyms: [
        "with loose cushions",
        "optional cushions",
        "detachable cushions",
        "removable cushions",
        "cushions included",
        "with add-on cushions",
        "optional throw cushions",
        "with free cushions",
        "cushions on demand",
        "loose-pillow option"
    ],
    spelling_variations: [
        "withoptionalloosecushions",
        "with optional loose cushions",
        "with-optional-loose-cushions",
        "with optionalloose cushions",
        "with optional loosecushions",
        "withoptional loose cushions",
        "withOptionalLooseCushions ",
        "withoptional loosecushions"
    ]
},
{
      feature: "Flared High Back",
    synonyms: [
        "splayed high back",
        "winged high back",
        "bell-top back",
        "trumpet high back",
        "flounce high back",
        "everted high back",
        "flared-tall back",
        "wide high back",
        "bell-shaped back",
        "flared tall back"
    ],
    spelling_variations: [
        "flaredhigh back",
        "flared highback",
        "flared high back ",
        "flared-high back",
        "flared high-back",
        "flare d high back",
        "flared high bac",
        "flaredhighback"
    ]
},
{
      feature: "Sloping Arms",
    synonyms: [
        "angled arms",
        "inclined arms",
        "raked arms",
        "leaning arms",
        "tilted arms",
        "slanted arms",
        "battered arms",
        "eased arms",
        "sloped armrests",
        "gradient arms"
    ],
    spelling_variations: [
        "slopingarms",
        "sloping arms ",
        "sloping-arms",
        "slopng arms",
        "slopeing arms",
        "sloping armss",
        "sloping arm s",
        "sloping   arms"
    ]
},
{
      feature: "Tubular Hollow Wooden Frame",
    synonyms: [
        "hollow tube wood frame",
        "tubular timber frame",
        "wooden tube chassis",
        "tube-structured wood",
        "hollow-wood tubing",
        "wood tubular skeleton",
        "timber tube frame",
        "cored wood tube frame",
        "pipe-like wood frame",
        "tubular wood support"
    ],
    spelling_variations: [
        "tubularhollow woodenframe",
        "tubular hollowwooden frame",
        "tubular hollow wooden frame ",
        "tubular-hollow wooden frame",
        "tubular hollow-wooden frame",
        "tubular hollow woodenframe",
        "tubular hollow wood frame"
    ]
},
{
      feature: "Pleated Back",
    synonyms: [
        "folded backrest",
        "gathered back",
        "pleat-detail back",
        "pinched-back",
        "accordion back",
        "tucked backrest",
        "pleated panel back",
        "ruched back",
        "pleat-pattern back",
        "pleat-trimmed back"
    ],
    spelling_variations: [
        "pleatedback",
        "pleated back ",
        "pleated-back",
        "pleated bck",
        "pleeted back",
        "pleated bak",
        "plaeated back",
        "pleated  back"
    ]
},
{
      feature: "Angular Back",
    synonyms: [
        "angled backrest",
        "geometric back",
        "faceted back",
        "sharp-back",
        "polygonal back",
        "triangular backrest",
        "edged back",
        "cornered back",
        "angular-profile back",
        "straight-angle back"
    ],
    spelling_variations: [
        "angularback",
        "angular back ",
        "angular-back",
        "anglular back",
        "angular bak",
        "angulr back",
        "angular  back",
        "angularb ack"
    ]
},
{
      feature: "Folded Arms",
    synonyms: [
        "pleated arms",
        "crease arms",
        "tucked arms",
        "fold-detail arms",
        "pinched arms",
        "wrapped arms",
        "overlay arms",
        "gathered arms",
        "origami-style arms",
        "fold-pattern arms"
    ],
    spelling_variations: [
        "foldedarms",
        "folded arms ",
        "folded-arms",
        "folded armss",
        "foled arms",
        "folded amrs",
        "folded arns",
        "foldd arms"
    ]
},
{
      feature: "Heavy Base",
    synonyms: [
        "solid base",
        "massive foundation",
        "weighted base",
        "substantial base",
        "sturdy base",
        "dense base",
        "robust foundation",
        "bulky base",
        "hefty base",
        "substantial plinth"
    ],
    spelling_variations: [
        "heavybase",
        "heavy base ",
        "heavy-base",
        "hevay base",
        "heavyb ase",
        "heavy bas",
        "heavy  base",
        "heavy-base "
    ]
},
{
      feature: "Sleek Arms",
    synonyms: [
        "slim arms",
        "streamlined arms",
        "svelte arms",
        "elegant arms",
        "smooth arms",
        "sleek-profile arms",
        "thin arms",
        "polished arms",
        "refined arms",
        "shapely arms"
    ],
    spelling_variations: [
        "sleekarms",
        "sleek arms ",
        "sleek-arms",
        "sleek armss",
        "sleak arms",
        "sleek amrs",
        "sleek arns",
        "sleek   arms"
    ]
},
{
      feature: "Straight Legs",
    synonyms: [
        "linear legs",
        "upright legs",
        "vertical legs",
        "plumb legs",
        "right-angle legs",
        "unbent legs",
        "direct legs",
        "straight-profile legs",
        "flush legs",
        "even legs"
    ],
    spelling_variations: [
        "straightlegs",
        "straight legs ",
        "straight-legs",
        "straigt legs",
        "streight legs",
        "straight legss",
        "straigh legs",
        "straight  legs"
    ]
},
{
      feature: "Planar Legs",
    synonyms: [
        "flat legs",
        "slab legs",
        "panel legs",
        "plate legs",
        "planed legs",
        "sheet legs",
        "plane legs",
        "planed-profile legs",
        "plank legs",
        "planar-profile legs"
    ],
    spelling_variations: [
        "planarlegs",
        "planar legs ",
        "planar-legs",
        "planer legs",
        "planar legss",
        "plan ar legs",
        "planar  legs",
        "planarleg s"
    ]
},
{
      feature: "Adjustable Back",
    synonyms: [
        "reclinable backrest",
        "tilt-back",
        "movable back",
        "adjustable tilt back",
        "height-adjust back",
        "flexible backrest",
        "modular back",
        "variable back angle",
        "pivot backrest",
        "customizable back"
    ],
    spelling_variations: [
        "adjustableback",
        "adjustable back ",
        "adjustable-back",
        "adjustble back",
        "adjustable bak",
        "adjustable bac k",
        "adjustable backk",
        "adjustable  back"
    ]
},
{
      feature: "Integrated Arms & Legs",
    synonyms: [
        "one-piece arms and legs",
        "unified supports",
        "monoblock frame",
        "integral limbs",
        "combined arms-legs",
        "arms-legs fusion",
        "joined arms and legs",
        "all-in-one supports",
        "fusion frame",
        "continuous limbs"
    ],
    spelling_variations: [
        "integratedarms&legs",
        "integrated arms & legs ",
        "integrated-arms & legs",
        "integrated arms and legs",
        "integrated arms &leg s",
        "integrated arms& legs",
        "integrated arms &legs",
        "integrated  arms & legs"
    ]
},
{
      feature: "upholstered structure",
    synonyms: [
        "padded framework",
        "cushioned structure",
        "fabric-clad frame",
        "upholstery frame",
        "soft-shell structure",
        "padded skeleton",
        "textile frame",
        "upholstered chassis",
        "cushioned skeleton",
        "fabric-wrapped frame"
    ],
    spelling_variations: [
        "upholsteredstructure",
        "upholstered structure ",
        "upholstered-structure",
        "uphostlered structure",
        "upholstered strcuture",
        "upholstered struc ture",
        "upholstered struture",
        "upholstered structre"
    ]
},
{
      feature: "armsWithMetalDetail",
    synonyms: [
        "metal-trim arms",
        "arms with metal accents",
        "metal-detailed arms",
        "arms with metal inlay",
        "metallined arms",
        "arms with metal trim",
        "metal-embellished arms",
        "arms with metal edging",
        "arms with metal finish",
        "arms with metal highlights"
    ],
    spelling_variations: [
        "armswithmetaldetail",
        "armsWithMetalDetail ",
        "arms-with-metal-detail",
        "arms with metal detail ",
        "armswithmetaldetail ",
        "armswith metaldetail",
        "arms-with metal detail",
        "armsWithMetal Dtail"
    ]
},
{
      feature: "Leather Piping",
    synonyms: [
        "leather welting",
        "leather trim",
        "leather-bound piping",
        "leather-edged seam",
        "leather accent piping",
        "leather cord trim",
        "leather welt",
        "leather seam piping",
        "leather border piping",
        "leather outline trim"
    ],
    spelling_variations: [
        "leatherpiping",
        "leather piping ",
        "leather-piping",
        "leather pipng",
        "lether piping",
        "leather pi ping",
        "leather pipin",
        "leatherpip ing",
        "leather piiping"
    ]
},
{
      feature: "Metal detail",
    synonyms: [
        "metal accent",
        "metallic trim",
        "metal embellishment",
        "metal highlight",
        "metal ornament",
        "metal inlay",
        "metal edging",
        "metal applique",
        "metal  feature",
        "metal decorative element"
    ],
    spelling_variations: [
        "metaldetail",
        "metal detail ",
        "metal-detail",
        "metal detial",
        "matal detail",
        "metal deatil",
        "metal detil",
        "metal detali"
    ]
},
{
      feature: "LShape",
    synonyms: [
        "L-shaped",
        "angle-shaped",
        "corner form",
        "right-angle profile",
        "L-profile",
        "L-configuration",
        "corner sectional",
        "elbow shape",
        "L-configuration frame",
        "L-structure"
    ],
    spelling_variations: [
        "L Shape",
        "L-Shape ",
        "LShape ",
        "L shape",
        "Lshape",
        "L-shape",
        "L shap",
        "lshape"
    ]
},
{
      feature: "Without Armrest",
    synonyms: [
        "armless",
        "no armrests",
        "open sides",
        "arm-free design",
        "armless profile",
        "no-side supports",
        "without arms",
        "arm-void",
        "armrest-less",
        "sans armrests"
    ],
    spelling_variations: [
        "withoutarmrest",
        "without armrest ",
        "without-armrest",
        "without arm rests",
        "wihout armrest",
        "without arm rest",
        "without armrests",
        "witout armrest"
    ]
},
{
      feature: "Modular Arm",
    synonyms: [
        "detachable arm",
        "interchangeable armrest",
        "reconfigurable arm",
        "modular armrest",
        "arm module",
        "slot-in arm",
        "arm component",
        "arm unit",
        "add-on armrest",
        "swap-out arm"
    ],
    spelling_variations: [
        "modulararm",
        "modular arm ",
        "modular-arm",
        "modular arms",
        "modualr arm",
        "modular armrest",
        "modulararm ",
        "moduler arm"
    ]
},
{
      feature: "Piping Follows Structure",
    synonyms: [
        "contour piping",
        "profile-tracing piping",
        "structure-lined piping",
        "outline piping",
        "form-fitting piping",
        "edge-mapped piping",
        "architecture-aligned piping",
        "frame-conforming piping",
        "shape-tracing welt",
        "structure-hugging piping"
    ],
    spelling_variations: [
        "pipingfollowsstructure",
        "piping follows structure ",
        "piping-follows-structure",
        "piping followsstructure",
        "piping-follow-structure",
        "pipingfollows structure",
        "piping followsstructure",
        "piping follow structure"
    ]
},
{
      feature: "LowBack",
    synonyms: [
        "low-back",
        "low-backrest",
        "short back",
        "low profile back",
        "shallow back",
        "mini backrest",
        "grounded back",
        "diminished back height",
        "compact back",
        "low-back seating"
    ],
    spelling_variations: [
        "low back",
        "low-back ",
        "lowback ",
        "lowbak",
        "low bac k",
        "lowb ack",
        "lowbackrest",
        "low-backrest"
    ]
},
{
      feature: "Metal Structure",
    synonyms: [
        "metal frame",
        "metal chassis",
        "steel structure",
        "iron framework",
        "aluminum skeleton",
        "metal substructure",
        "metal build",
        "steel framework",
        "metal body",
        "metal support frame"
    ],
    spelling_variations: [
        "metalstructure",
        "metal structure ",
        "metal-structure",
        "metal strucuture",
        "metal structre",
        "metl structure",
        "metalstructure ",
        "metal shuffle"
    ]
},
{
      feature: "Splayed Arms",
    synonyms: [
        "flared arms",
        "splayed-profile arms",
        "winged arms",
        "outward-leaning arms",
        "bell arms",
        "trumpet arms",
        "everted arms",
        "flounce arms",
        "flared-edge arms",
        "splayed-armrests"
    ],
    spelling_variations: [
        "splayedarms",
        "splayed arms ",
        "splayed-arms",
        "splaed arms",
        "splayd arms",
        "splayed armss",
        "splayed arm",
        "splayed arm s"
    ]
},
{
      feature: "Quilted Back",
    synonyms: [
        "tufted back",
        "diamond-quilt back",
        "panel-quilt back",
        "channel-quilt back",
        "padded quilt back",
        "quilted-panel back",
        "stitched quilt back",
        "cushioned quilt back",
        "grid-quilt back",
        "box-quilt back"
    ],
    spelling_variations: [
        "quiltedback",
        "quilted back ",
        "quilted-back",
        "quilted bak",
        "quiltd back",
        "quilted bck",
        "quiltted back",
        "quiltedback "
    ]
},
{
      feature: "Upholstered Plinth",
    synonyms: [
        "padded plinth",
        "cushioned base plinth",
        "fabric-covered plinth",
        "upholstery plinth",
        "textile plinth",
        "soft plinth",
        "upholstered pedestal",
        "padded pedestal",
        "cushioned plinth",
        "upholstered sub-base"
    ],
    spelling_variations: [
        "upholsteredplinth",
        "upholstered plinth ",
        "upholstered-plinth",
        "upholstered plint",
        "upholsterd plinth",
        "upholstered plinthh",
        "uphplstered plinth",
        "upholstered plinth "
    ]
},
{
      feature: "Flat Piping",
    synonyms: [
        "slim welt",
        "flat welt trim",
        "flat seam piping",
        "low-profile piping",
        "flat-edge piping",
        "tape piping",
        "flat binding",
        "flat seam trim",
        "flush piping",
        "flat border piping"
    ],
    spelling_variations: [
        "flatpiping",
        "flat piping ",
        "flat-piping",
        "flat pipng",
        "fl at piping",
        "flat piiping",
        "flatpip ing",
        "flat pipin"
    ]
},
{
      feature: "Floor Length Arms",
    synonyms: [
        "full-drop arms",
        "floor-to-arm arms",
        "floor-reaching arms",
        "floor-sweeping arms",
        "long arms",
        "floor-touch arms",
        "floor-base arms",
        "ground-length arms",
        "floor-contact arms",
        "floor-hugging arms"
    ],
    spelling_variations: [
        "floorlengtharms",
        "floor length arms ",
        "floor-length arms",
        "floor lengh arms",
        "floorlength arms",
        "floor length-arms",
        "floor-lengtharms",
        "floorl ength arms"
    ]
},
{
      feature: "BackCushionsIntegral",
    synonyms: [
        "integral back cushions",
        "built-in back cushions",
        "fixed back cushions",
        "one-piece back cushions",
        "attached back cushions",
        "inbuilt back cushions",
        "seamless back cushions",
        "monolithic back cushions",
        "cushion-integrated back",
        "permanent back cushions"
    ],
    spelling_variations: [
        "backcushionsintegral",
        "back cushions integral",
        "back-cushions-integral",
        "backcushions integral",
        "back cushionsintegral",
        "back cushion sintegral",
        "backcushionsintegral ",
        "backcushions-integral"
    ]
},
{
      feature: "curvedArms",
    synonyms: [
        "rounded arms",
        "arched arms",
        "circular arms",
        "oval arms",
        "swept arms",
        "bowed arms",
        "contoured arms",
        "tubular arms",
        "radius arms",
        "semi-circular arms"
    ],
    spelling_variations: [
        "curvedarms",
        "curved arms ",
        "curved-arms",
        "curved armss",
        "crved arms",
        "curvd arms",
        "curve d arms",
        "curvedarm s"
    ]
},
{
      feature: "HighBack",
    synonyms: [
        "high-back",
        "tall backrest",
        "lofted back",
        "elevated back",
        "tower back",
        "skyline back",
        "raised backrest",
        "extended back",
        "soaring backrest",
        "lofty back"
    ],
    spelling_variations: [
        "high back",
        "high-back ",
        "highback ",
        "hig back",
        "highbak",
        "hightback",
        "highbac k",
        "high-backrest"
    ]
},
{
      feature: "Wing Back Design",
    synonyms: [
        "winged back",
        "batwing back",
        "ear-back design",
        "wingback",
        "paired-wing back",
        "flared-wing back",
        "side-wing back",
        "cradle back",
        "winged headrest",
        "wing-backrest"
    ],
    spelling_variations: [
        "wingbackdesign",
        "wing back design ",
        "wing-back design",
        "wingback design",
        "wing-backdesign",
        "wing backdesign",
        "wingback-des ign",
        "wingbackde sign"
    ]
},
{
      feature: "Curvilinear Back",
    synonyms: [
        "sinuous back",
        "curved-profile back",
        "wavy backrest",
        "undulating back",
        "flowing back",
        "organic back",
        "meandering back",
        "arc backrest",
        "ribbon back",
        "curved contour back"
    ],
    spelling_variations: [
        "curvilinearback",
        "curvilinear back ",
        "curvilinear-back",
        "curvlinear back",
        "curvilinear bak",
        "curvilinearbac k",
        "curvelinear back",
        "curvillinear back"
    ]
},
{
      feature: "Polyurethane",
    synonyms: [
        "PU foam",
        "urethane",
        "poly foam",
        "polymer foam",
        "PU material",
        "flexible foam",
        "rigid foam",
        "polymer cushioning",
        "poly-foam",
        "PU upholstery"
    ],
    spelling_variations: [
        "polyurethane ",
        "polyureth ane",
        "polyurethann",
        "polyurthane",
        "polyurethne",
        "polyurethane",
        "polyurethene",
        "polyureth ane "
    ]
},
{
      feature: "Back Cushions Integral to Sofa",
    synonyms: [
        "sofa-integral back cushions",
        "built-in sofa cushions",
        "sofa-fixed back cushions",
        "one-piece sofa cushions",
        "attached sofa cushions",
        "inbuilt sofa cushions",
        "sofa seam-back cushions",
        "monolithic sofa cushions",
        "sofa cushion–integral back",
        "permanent sofa cushions"
    ],
    spelling_variations: [
        "backcushionsintegraltoSofa",
        "back cushions integral to sofa",
        "back-cushions-integral-to-sofa",
        "backcushions integral to sofa",
        "back cushionsintegralto sofa",
        "back cushions integralsofa",
        "back cushions integral tosofa",
        "backcushionsintegralto sofa"
    ]
},
{
      feature: "External Metal Embellishments",
    synonyms: [
        "metal studs",
        "rivets",
        "metallic appliques",
        "metal accents",
        "metal trims",
        "metal inlays",
        "metal overlays",
        "metal filigree",
        "metal motifs",
        "metal rosettes",
        "external metal trims",
        "external metallic accents",
        "metal corner caps",
        "metal corner protectors",
        "architectural metal accents",
        "metal leaf embellishments",
        "metal banding",
        "metal stud trim",
        "exposed metalwork",
        "visible metalwork",
        "decorative metal straps",
        "metal bracket embellishments",
        "metal edge trim",
        "metal strap accents",
        "metal panel detailing"
    ],
    spelling_variations: [
        "externalmetalembellishments",
        "external metal embellishments ",
        "external-metal-embellishments",
        "external metal embelishments",
        "external metel embellishments",
        "external metal embelishmnts",
        "external metal embelishmts",
        "externalmetal embellishments",
        "external metal embelmishments",
        "external metal embelishents",
        "external metal embelmshents",
        "externalmet alembellishments",
        "external met al embellishments",
        "external-metalembellishments",
        "external metalembellishments"
    ]
},
{
      feature: "Pebble",
    synonyms: [
        "pebble shape",
        "pebble-like",
        "pebble pattern",
        "pebble motif",
        "pebble-textured",
        "pebble finish",
        "pebble form",
        "pebble profile",
        "pebble silhouette",
        "pebble contour",
        "pebble surface",
        "pebble effect",
        "pebble-inspired",
        "stone-like",
        "pebblegrain texture",
        "pebblegrain finish",
        "pebblegrain motif",
        "pebblegrain pattern",
        "round pebble form",
        "oval pebble outline",
        "pebble cushion style",
        "pebble ottoman shape",
        "pebble pouf design",
        "pebble-edge detailing",
        "pebbleback style"
    ],
    spelling_variations: [
        "pebble",
        "pebbel",
        "pebbble",
        "pble",
        "peb le",
        "pebb;e",
        "pebbel ",
        "pebb le",
        "pebble ",
        "pebblee",
        "pebble-",
        "peb ble",
        "pebb le",
        "peblle"
    ]
},
{
      feature: "Nail Trimming And Nail Buttons",
    synonyms: [
        "nailhead trim",
        "studded trim",
        "nailhead studs",
        "nailhead accents",
        "stud trim",
        "tack trim",
        "nailhead edging",
        "nailhead border",
        "nailhead detailing",
        "nail-head trim",
        "metal stud trimming",
        "upholstery nails",
        "upholstery tacks",
        "nail-head studs",
        "tack buttons",
        "decorative tacks",
        "button nails",
        "nailhead applique",
        "nailhead pattern",
        "tack border",
        "brass nail trim",
        "nickel nail trim",
        "silver nail trim",
        "antique nail trim",
        "colored nail trim"
    ],
    spelling_variations: [
        "nailtrimmingandnailbuttons",
        "nail trimming and nail buttons ",
        "nail-trimming and nail-buttons",
        "nail head trim",
        "nailhead trim",
        "nail trimming & nail buttons",
        "nail trimming and nails buttons",
        "nail trimming and nailbutons",
        "nail trimming and nail butttons",
        "nail trimming an nail buttons",
        "nail trimming and nal buttons",
        "nail trimming and nail butons",
        "nail trimming and nail butons",
        "nail trimmingandnailbuttons",
        "nail trimming and nail butons"
    ]
},
{
      feature: "OptionalQuiltedLooseCushions",
    synonyms: [
        "optional quilted cushions",
        "optional loose quilted cushions",
        "detachable quilted cushions",
        "removable quilted cushions",
        "quilted throw cushions",
        "quilted loose pillows",
        "quilted cushion inserts",
        "quilted pillow options",
        "loose quilted pillows",
        "add-on quilted cushions",
        "quilted cushion modules",
        "quilted pillow extras",
        "quilted cushioned throws",
        "loose quilt cushions",
        "quilted bolsters",
        "quilted scatter cushions",
        "optional quilt pillows",
        "quilted accent pillows",
        "quilted soft cushions",
        "quilted pad options",
        "quilted comfort cushions",
        "quilted fill pillows",
        "quilted topper cushions",
        "quilted cushion add-ons",
        "quilted cushion pack"
    ],
    spelling_variations: [
        "optionalquiltedloosecushions",
        "optional quilted loose cushions ",
        "optional-quilted-loose-cushions",
        "optionalquilted loose cushions",
        "optional quiltedloose cushions",
        "optional quilt loose cushions",
        "optional quilt loosecushions",
        "optional quilted loosecushions",
        "optional quilted loose cushion",
        "optional quilted loose coushions",
        "optional quilted loose cushiouns",
        "optional quilted loose cushins",
        "optional quiltedloosecushions",
        "optional quilted loose cushiosn"
    ]
},
{
      feature: "Circular",
    synonyms: [
        "round",
        "circular profile",
        "ring-shaped",
        "orbicular",
        "disc-like",
        "circle-shaped",
        "radial form",
        "concentric profile",
        "circular silhouette",
        "circular contour",
        "circular frame",
        "circular motif",
        "circular design",
        "circular outline",
        "circular pattern",
        "circular edge",
        "donut-shaped",
        "circular geometry",
        "circular element",
        "circular seat",
        "circular back",
        "circular armrest",
        "circular base",
        "circular feet",
        "circular panel"
    ],
    spelling_variations: [
        "circluar",
        "ciruclar",
        "circular ",
        "circular-",
        "cicular",
        "circllar",
        "circularr",
        "circluar ",
        "circulare",
        "circllar ",
        "cicular ",
        "ciruclar "
    ]
},
{
      feature: "Curved Back",
    synonyms: [
        "arched back",
        "contoured backrest",
        "curved-profile back",
        "serpentine backrest",
        "convex back",
        "concave back",
        "radius back",
        "flowing back",
        "bowback",
        "barrelback",
        "wavy back",
        "curved contour back",
        "curved-shell back",
        "ergonomic back",
        "curved-form back",
        "curved silhouette",
        "enveloping back",
        "wrap-back",
        "cradle backrest",
        "curved support",
        "curved upholstered back",
        "smooth curved back",
        "curved ergonomic profile",
        "curved wooden back",
        "curved metal back"
    ],
    spelling_variations: [
        "curvedback",
        "curved back ",
        "curved-back",
        "curved bak",
        "curved bac",
        "cruvd back",
        "curvd back",
        "curvedb ack",
        "curvved back",
        "curved ba ck",
        "curvedbac k",
        "curved-ba ck"
    ]
},
{
      feature: "Rounded Back",
    synonyms: [
        "curved backrest",
        "roll-back",
        "barrel back",
        "bulbous back",
        "arched backrest",
        "circular back",
        "contoured back",
        "rounded-profile back",
        "smooth back",
        "pillowed back",
        "enveloping back",
        "cloud back",
        "padback",
        "tub-back",
        "organic back",
        "radius backrest",
        "ergonomic back",
        "loop-back",
        "scoop-back",
        "archback",
        "looped backrest",
        "barrel-shaped back",
        "rounded silhouette",
        "bubble-back",
        "dome-back"
    ],
    spelling_variations: [
        "roundedback",
        "rounded back ",
        "rounded-back",
        "rounded bakc",
        "roundd back",
        "roundrd back",
        "roundedbac k",
        "rounded ba ck",
        "roundedbak",
        "roundedbac",
        "rounded-ba ck",
        "rounded–back"
    ]
},
// sofa with rounded back
{
      feature: "Dual Tone",
    synonyms: [
        "two-tone",
        "bi-color",
        "dual-color",
        "two-colour",
        "bi-tone",
        "two-shade",
        "dual-shade",
        "contrast-tone",
        "two-tone finish",
        "dual-hue",
        "twin-tone",
        "two-tone palette",
        "two-tone upholstery",
        "bi-color trim",
        "two-tone piping",
        "two-tone stitching",
        "two-tone surface",
        "two-tone pattern",
        "dual-tone design",
        "two-tone detail",
        "two-tone motif",
        "twin-color",
        "twin-shade",
        "bicolor",
        "duotone"
    ],
    spelling_variations: [
        "dualtone",
        "dual-tone",
        "dual tone ",
        "duall tone",
        "dual ton",
        "dual-tone ",
        "dualt one",
        "dualton e",
        "dual-ton e",
        "dual-tonee",
        "dual-tonee ",
        "dual-tone–"
    ]
},
{
      feature: "Two Tone Piping",
    synonyms: [
        "bi-color piping",
        "dual-color piping",
        "two-tone welting",
        "two-tone trim",
        "contrast piping",
        "bicolor piping",
        "twin-tone piping",
        "dual-tone welt",
        "split-tone piping",
        "two-tone cord",
        "two-tone border",
        "two-tone outline",
        "two-tone seam",
        "two-tone cable",
        "two-tone edge",
        "two-tone accent piping",
        "two-tone profile piping",
        "two-tone stitch",
        "two-tone braiding",
        "two-tone seaming",
        "two-tone welt trim",
        "two-tone braid",
        "dual-tone piping",
        "bi-tone piping",
        "twin-color piping"
    ],
    spelling_variations: [
        "twotonepiping",
        "two tone piping",
        "two-tone-piping",
        "twotone piping",
        "two-tone piping ",
        "two tone-pipng",
        "two-tonepipng",
        "two-tonepipng ",
        "two-tonepipingg",
        "two-tone-piping",
        "two-tone–piping",
        "two-tone piping"
    ]
},
{
      feature: "CShape",
    synonyms: [
        "C-shaped",
        "c-profile",
        "C-form",
        "c-curved",
        "C-contour",
        "C-profile frame",
        "c-frame",
        "c-curve",
        "c-back",
        "c-arm",
        "c-leg",
        "c-seat",
        "C-structure",
        "C-motif",
        "c-silhouette",
        "c-arch",
        "C-shape design",
        "c-architecture",
        "c-section",
        "c-shape frame",
        "c-shaped silhouette",
        "c-frame structure",
        "c-moulding",
        "c-edge",
        "c-outline"
    ],
    spelling_variations: [
        "cshape",
        "CShape",
        "C-shape",
        "C shape",
        "c-shape",
        "cshape ",
        "c shap",
        "c-shape",
        "C-shape",
        "csh ape",
        "c-shap",
        "c-shap e"
    ]
},
{
      feature: "Elevated Arms",
    synonyms: [
        "raised arms",
        "high arms",
        "lifted armrests",
        "elevated armrests",
        "upraised arms",
        "elevated-profile arms",
        "armrests on risers",
        "elevated-side supports",
        "high-position arms",
        "armrests at height",
        "tall arms",
        "elevated-edge arms",
        "raised-side arms",
        "elevated-frame arms",
        "lifted-profile arms",
        "raised-support arms",
        "high-set arms",
        "elevated bracket arms",
        "elevated mount arms",
        "uplifted arms",
        "elevated structure arms",
        "elevated-platform arms",
        "elevated skeleton arms",
        "elevated chassis arms",
        "armrests on stilts"
    ],
    spelling_variations: [
        "elevatedarms",
        "elevated arms ",
        "elevated-arms",
        "eleveted arms",
        "elevatd arms",
        "elevated armss",
        "elevatd-arms",
        "elevated arm s",
        "elevated  arms",
        "elvated arms"
    ]
},
{
      feature: "Leather",
    synonyms: [
        "hide upholstery",
        "leatherette",
        "genuine leather",
        "aniline leather",
        "top-grain leather",
        "full-grain leather",
        "bonded leather",
        "PU leather",
        "faux leather",
        "eco-leather",
        "nappa leather",
        "suede leather",
        "nubuck leather",
        "corrected-grain leather",
        "split leather",
        "leather finish",
        "leather covering",
        "leather material",
        "leather textile",
        "leather surface",
        "leather skin",
        "leather hide",
        "leather wrap",
        "leather cladding",
        "leather trim"
    ],
    spelling_variations: [
        "leather ",
        "lether",
        "leather-",
        "leathr",
        "lether ",
        "leathaer",
        "lether",
        "lather",
        "leat her",
        "leathe r"
    ]
},
{
      feature: "Grid Tufted Arms",
    synonyms: [
        "paneled tufted arms",
        "square tuft arms",
        "box tuft arms",
        "grid-pattern armrest",
        "matrix tuft arms",
        "checker tuft arms",
        "cubic tuft arms",
        "grid-quilted arms",
        "panel-quilt arms",
        "block tuft arms",
        "grid-quilt armrests",
        "square-channel arms",
        "gridset tuft arms",
        "gridline tuft arms",
        "gridback arms",
        "panel-tuft arms",
        "checkerboard arms",
        "geometric tuft arms",
        "grid stitch arms",
        "grid-stitched arms",
        "grid-quilt profile arms",
        "grid-lattice arms",
        "grid-section arms",
        "grid-panel arms",
        "grid-quilt overlay arms"
    ],
    spelling_variations: [
        "gridtuftedarms",
        "grid tufted arms ",
        "grid-tu fted arms",
        "grid tufted-arms",
        "gridtufted arms",
        "grid tuftedarm s",
        "grid tufted armss",
        "grid tuftedar ms",
        "gridtuftedar ms",
        "grid tufted arm"
    ]
},
{
      feature: "Quilted Arms",
    synonyms: [
        "tufted arms",
        "diamond-quilt arms",
        "channel-quilt arms",
        "panel-quilt arms",
        "cushioned quilt arms",
        "quilted-panel arms",
        "stitched quilt arms",
        "grid-quilt arms",
        "box-quilt arms",
        "pin-tuck arms",
        "ruched quilt arms",
        "pleated quilt arms",
        "piped quilt arms",
        "quilting-detail arms",
        "padded-quilt arms",
        "buffered quilt arms",
        "quilted-edge arms",
        "quilt-pattern arms",
        "quilt-stitched arms",
        "quilted-overlay arms",
        "cable-quilt arms",
        "ribbon-quilt arms",
        "flanged-quilt arms",
        "ribbed-quilt arms",
        "soft-quilt arms"
    ],
    spelling_variations: [
        "quiltedarms",
        "quilted arms ",
        "quilted-arms",
        "quiltd arms",
        "quiltted arms",
        "quilted armss",
        "quilted arm s",
        "quiltedar ms",
        "quilt ed arms",
        "quil tedarms"
    ]
},
{
      feature: "Wooden Legs",
    synonyms: [
        "timber legs",
        "wood legs",
        "solid wood legs",
        "oak legs",
        "walnut legs",
        "maple legs",
        "beech legs",
        "ash legs",
        "birch legs",
        "wooden posts",
        "wooden uprights",
        "wood pillars",
        "wooden stilts",
        "wood pegs",
        "wood struts",
        "wooden supports",
        "wooden columns",
        "wooden shafts",
        "wood beams",
        "wood dowels",
        "wooden feet",
        "wood pedestals",
        "hardwood legs",
        "softwood legs",
        "wood frame legs"
    ],
    spelling_variations: [
        "woodenlegs",
        "wooden legs ",
        "wooden-legs",
        "wooden legss",
        "wodden legs",
        "wooden leg",
        "wooden leg s",
        "woodenleg s",
        "woodenlegg"
    ]
},
{
      feature: "Inclined Seat",
    synonyms: [
        "sloped seat",
        "angled seat",
        "raked seat",
        "tilted seat",
        "leaning seat",
        "graded seat",
        "eased seat",
        "ramped seat",
        "inclining seat",
        "slope-front seat",
        "bias seat",
        "slanted cushion",
        "inclined-profile seat",
        "sloped-profile seat",
        "tilt-back seat",
        "front-drop seat",
        "rear-rise seat",
        "elevated rear seat",
        "lower front seat",
        "angled-profile seat",
        "graded-profile seat",
        "sloped shell seat",
        "cant seat",
        "cantilevered seat",
        "inclined surface seat"
    ],
    spelling_variations: [
        "inclinedseat",
        "inclined seat ",
        "inclined-seat",
        "inclind seat",
        "incline d seat",
        "inclined seats",
        "incline seat",
        "inclinedse at",
        "inclined seatt"
    ]
},
{
      feature: "Metal Frame Arms",
    synonyms: [
        "metal-structured arms",
        "frame-metal arms",
        "metal chassis arms",
        "steel-frame arms",
        "iron-frame armrests",
        "aluminum-frame arms",
        "metal skeleton arms",
        "metal armature arms",
        "metalwork arms",
        "tubular-frame arms",
        "metal bracket arms",
        "metal rail arms",
        "metal strut arms",
        "wire-frame arms",
        "rod-frame arms",
        "metal beam arms",
        "metal brace arms",
        "metal framework arms",
        "metal profile arms",
        "metal outline arms",
        "structural metal arms",
        "industrial metal arms",
        "architectural arms",
        "metal construction arms",
        "metal grid arms"
    ],
    spelling_variations: [
        "metalframearms",
        "metal frame arms ",
        "metal-frame-ar ms",
        "metalframe arms",
        "metaframe arms",
        "metal frame armss",
        "metal-frame arms",
        "metal framearm s",
        "metal fra me arms"
    ]
},
{
      feature: "Wooden Arms",
    synonyms: [
        "timber armrests",
        "wood arms",
        "solid wood arms",
        "oak armrests",
        "walnut arms",
        "maple arm supports",
        "beech arms",
        "ash armrests",
        "birch arms",
        "wooden arm modules",
        "wooden arm panels",
        "hardwood arms",
        "softwood arms",
        "wood arm brackets",
        "wood arm frames",
        "wood arm shells",
        "wood arm covers",
        "wood arm mounts",
        "wood arm fittings",
        "wood arm overlays",
        "wood arm trims",
        "wood arm cladding",
        "wood arm detailing",
        "wood arm embellishments",
        "wood arm fillets"
    ],
    spelling_variations: [
        "woodenarms",
        "wooden arms ",
        "wooden-arms",
        "wodden arms",
        "wooden armss",
        "wooden arm s",
        "woodenarm s",
        "woodenarmss"
    ]
},
{
      feature: "Wooden Base",
    synonyms: [
        "timber base",
        "wood base",
        "solid wood base",
        "oak base",
        "walnut base",
        "maple base",
        "beech base",
        "ash base",
        "birch base",
        "wood foundation",
        "wooden plinth",
        "wooden pedestal",
        "hardwood base",
        "softwood base",
        "wood slab base",
        "wood block base",
        "wood support base",
        "wood frame base",
        "wood platform",
        "wood chassis base",
        "wood sub-base",
        "wood trim base",
        "wood bed base",
        "wood seating base",
        "wood block support"
    ],
    spelling_variations: [
        "woodenbase",
        "wooden base ",
        "wooden-base",
        "wodden base",
        "wooden bases",
        "wooden bas",
        "woodenba se",
        "wooden b ase"
    ]
},
{
      feature: "Low Armrest",
    synonyms: [
        "low-profile armrest",
        "short armrest",
        "low-set arms",
        "low-side supports",
        "dropped arms",
        "recessed armrests",
        "low-level arms",
        "low-stage arms",
        "low-mounted arms",
        "low-tier arms",
        "low-rise armrests",
        "stunted arms",
        "stubby arms",
        "grounded arms",
        "mini armrests",
        "compact arms",
        "modest arms",
        "low-grade arms",
        "floor-near arms",
        "semi-recessed arms",
        "under-armrest",
        "low-slung arms",
        "shallow arms",
        "low-profile rests",
        "low station arms"
    ],
    spelling_variations: [
        "lowarmrest",
        "low armrest ",
        "low-armrest",
        "low arm rests",
        "low-arm rests",
        "lo armrest",
        "lowarm rest",
        "low-armrest ",
        "lowarmre st"
    ]
},
{
      feature: "Planar Base",
    synonyms: [
        "flat base",
        "planed base",
        "slab base",
        "panel base",
        "plate base",
        "sheet base",
        "plane base",
        "planar-profile base",
        "plank base",
        "flat-profile base",
        "panel-profile base",
        "planar-support base",
        "planar-platform base",
        "planar-frame base",
        "planar-chassis base",
        "planar-structure base",
        "planar-skeleton base",
        "planar-shell base",
        "planar-block base",
        "planar-pedestal base",
        "planar-plinth base",
        "planar-platform",
        "planar-foundation",
        "planar-footing",
        "planar-support"
    ],
    spelling_variations: [
        "planarbase",
        "planar base ",
        "planar-base",
        "planar bas",
        "planar ba se",
        "planr base",
        "planarb ase",
        "planar-binse"
    ]
},
{
      feature: "Asymmetric Back",
    synonyms: [
        "uneven backrest",
        "off-center back",
        "lopsided back",
        "non-symmetrical back",
        "irregular backrest",
        "asym back",
        "skewed back",
        "bias backrest",
        "one-sided back",
        "asymmetrical backrest",
        "unbalanced back",
        "unequal back panels",
        "asym panel back",
        "irregular-panel back",
        "asym shell back",
        "off-balance back",
        "nonuniform back",
        "asym contour back",
        "asym-profile back",
        "asym silhouette back",
        "asym form back",
        "crooked backrest",
        "twisted back",
        "askew backrest",
        "off-axis back"
    ],
    spelling_variations: [
        "asymmetricback",
        "asymmetric back ",
        "asymmetric-back",
        "asymetric back",
        "asymmetrical back",
        "asymmetirc back",
        "asymmetricback ",
        "asymetric-back",
        "asymetricback",
        "asymmetric-bakc"
    ]
},
{
      feature: "Wooden structure",
    synonyms: [
        "timber structure",
        "wood framework",
        "wooden frame",
        "timber chassis",
        "wood skeleton",
        "wood substructure",
        "wood build",
        "timber frame",
        "wood support frame",
        "wooden chassis",
        "wood body",
        "wood architecture",
        "wooden shell",
        "wooden skeleton",
        "wood veneered structure",
        "solid wood structure",
        "laminated wood structure",
        "glulam structure",
        "post-and-beam frame",
        "timber-framed structure",
        "wood joint structure",
        "wood stave structure",
        "wood joinery frame",
        "mortise-and-tenon frame",
        "wood truss structure"
    ],
    spelling_variations: [
        "woodenstructure",
        "wooden structure ",
        "wooden-structure",
        "wodden structure",
        "wooden structre",
        "wooden struc ture",
        "woodenstr ucture",
        "wooden struture",
        "woodenstructure "
    ]
},
{
      feature: "Tubular Arms",
    synonyms: [
        "tube arms",
        "tubular armrests",
        "pipe arms",
        "circular-tube arms",
        "hollow-tube arms",
        "tubing arms",
        "tube-profile arms",
        "tubular-profile arms",
        "pipe-frame arms",
        "tube-frame arms",
        "tubular-support arms",
        "rod arms",
        "bar arms",
        "tube-structure arms",
        "tubular-shell arms",
        "cylindrical arms",
        "round-tube arms",
        "metal-tube arms",
        "tubular-skeleton arms",
        "tube-work arms",
        "tube-motif arms",
        "tubular-outline arms",
        "hollow-rod arms",
        "pipe-outline arms",
        "tubular-chassis arms"
    ],
    spelling_variations: [
        "tubulararms",
        "tubular arms ",
        "tubular-arms",
        "tubular armss",
        "tubular arm s",
        "tubuar arms",
        "tubulararms ",
        "tubular–arms",
        "tublar arms",
        "tubular arm"
    ]
},
{
      feature: "Angular",
    synonyms: [
        "sharp-edged",
        "angled",
        "geometric",
        "faceted",
        "orthogonal",
        "polygonal",
        "rectilinear",
        "cornered",
        "right-angled",
        "linear",
        "edged",
        "cornered-profile",
        "angled-profile",
        "blocky",
        "chiseled",
        "bevelled",
        "beveled",
        "crisp-edged",
        "triangular",
        "quadrilateral",
        "hexagonal",
        "polygonal-form",
        "angular-contour",
        "angled-silhouette",
        "angular-outline"
    ],
    spelling_variations: [
        "angular ",
        "angluar",
        "angular-",
        "anglar",
        "angularr",
        "angular  ",
        "angular–",
        "angluar "
    ]
},
{
      feature: "Metal Bar Structure Around Back",
    synonyms: [
        "back metal bar frame",
        "metal surround back",
        "bar-back frame",
        "metal bar backrest",
        "metal hoop back",
        "backrest metal cage",
        "metal rail back support",
        "metal arc back",
        "back metal loop",
        "metal rod back surround",
        "barred back frame",
        "metal-back enclosure",
        "metal-back guard",
        "metal-back railing",
        "metal-back band",
        "metal-back bracket",
        "metal-back arch",
        "back bar chassis",
        "back bar skeleton",
        "metal-back bracketry",
        "metal-back reinforcement",
        "metal-back casting",
        "metal-back cradle",
        "bar-encased back",
        "metal-back trim",
        "metal-back accent"
    ],
    spelling_variations: [
        "metalbarstructurearoundback",
        "metal bar structure around back ",
        "metal-bar-structure-around-back",
        "metal barstructure around back",
        "metal bar structurearound back",
        "metal barstructurearound back",
        "metalbar structurearoundback",
        "metalbankstructurearoundback",
        "metal bar structure aroundback",
        "metal bar structurearoundback"
    ]
},
{
      feature: "External Wood Embellishments",
    synonyms: [
        "wood appliques",
        "wood trims",
        "wood overlays",
        "wood filigree",
        "wood motifs",
        "wood corbels",
        "wood brackets",
        "wood rosettes",
        "wood medallions",
        "wood studs",
        "wood carvings",
        "wood inlays",
        "wood panels",
        "wood ornamentation",
        "wood dentil trim",
        "wood fretwork",
        "wood mouldings",
        "wood scrollwork",
        "wood fillets",
        "wood accents",
        "wood strapwork",
        "wood banding",
        "wood beads",
        "wood keystone",
        "wood fascia",
        "wood cresting"
    ],
    spelling_variations: [
        "externalwoodembellishments",
        "external wood embellishments ",
        "external-wood-embellishments",
        "external wood embelishments",
        "externall wood embellishments",
        "externalwood embellishments",
        "external woodembellishments",
        "externalwo od embellishments",
        "external wood embelshments"
    ]
},
{
      feature: "Plain",
    synonyms: [
        "simple",
        "unadorned",
        "minimal",
        "clean",
        "bare",
        "smooth",
        "flat",
        "plain-surfaced",
        "undecorated",
        "unembellished",
        "straightforward",
        "basic",
        "elemental",
        "unornamented",
        "no-frills",
        "austere",
        "spartan",
        "barebones",
        "stark",
        "natural",
        "raw",
        "polished",
        "plain-finish",
        "plain-design",
        "plain-style",
        "uncluttered"
    ],
    spelling_variations: [
        "plain ",
        "plain-",
        "plainn",
        "plian",
        "pplain",
        "plain  ",
        "pl ain",
        "plian ",
        "pla in"
    ]
},
{
      feature: "Asymmetric Curve",
    synonyms: [
        "uneven curve",
        "off-center curve",
        "lopsided curve",
        "non-symmetrical curve",
        "irregular curve",
        "skewed curve",
        "bias curve",
        "one-sided curve",
        "asymmetrical curve",
        "crooked curve",
        "twisted curve",
        "askew curve",
        "biased curvature",
        "off-axis curve",
        "unequal curve bend",
        "asym contour",
        "asym-profile curve",
        "uneven bend",
        "nonuniform curve",
        "skewed-profile curve",
        "irregular-contour curve",
        "asym silhouette curve",
        "off-balance curve",
        "crooked-contour",
        "biased-bend"
    ],
    spelling_variations: [
        "asymmetriccurve",
        "asymmetric curve ",
        "asymmetric-curve",
        "asymetric curve",
        "asymmetricalcurve",
        "asymetric-curve",
        "asymmetriccur ve",
        "asymmetric cur ve",
        "asymmetric cu rve"
    ]
},
{
      feature: "ContrastPiping",
    synonyms: [
        "contrast welt",
        "contrast trim piping",
        "contrast cord piping",
        "contrast-edge piping",
        "contrast border piping",
        "contrast welting",
        "contrast seam piping",
        "contrast-color piping",
        "contrast-stitch piping",
        "contrast welt trim",
        "accent piping",
        "highlight piping",
        "outline piping",
        "piping contrast",
        "color-pop piping",
        "edge-highlight piping",
        "border-contrast piping",
        "welt-contrast piping",
        "trim-contrast piping",
        "contrast braid piping",
        "contrast tape piping",
        "contrast piping detail",
        "two-tone piping",
        "contrast seam trim",
        "contrast-cable piping"
    ],
    spelling_variations: [
        "contrastpiping",
        "contrast piping ",
        "contrast-piping",
        "contrast pipng",
        "contrst piping",
        "contrast piiping",
        "contrastpi ping",
        "contrast / piping",
        "contrast-pipng"
    ]
},
{
      feature: "Split back/Division",
    synonyms: [
        "divided back",
        "back split",
        "split-back design",
        "two-part backrest",
        "dual-panel back",
        "back segmentation",
        "bisected back",
        "back cleft",
        "back division",
        "split-panel back",
        "back bifurcation",
        "split-backrest",
        "back in two sections",
        "backrest split",
        "split-back support",
        "double-back design",
        "back split detail",
        "back seam division",
        "backrest segmentation",
        "two-piece backrest",
        "split-cushion back",
        "split-back cushion",
        "segmented backrest",
        "divided-back cushion",
        "back split motif"
    ],
    spelling_variations: [
        "splitback/division",
        "split backdivision",
        "split-backdivision",
        "split back division ",
        "splitback division",
        "split–back/division",
        "split back/division",
        "splitback/division ",
        "split backdivision ",
        "split–back division",
        "split back—division",
        "splitbackdivision",
        "split-back division",
        "split back/division",
        "splitback division"
    ]
},
{
      feature: "Button Tacked Back",
    synonyms: [
        "tacked-back buttons",
        "button-tuft backrest",
        "button-backed",
        "button tack tufting",
        "button-studded back",
        "back with tacks",
        "nail-button back",
        "button-brad back",
        "tack-button backrest",
        "button-pin back",
        "button-pin tufting",
        "tacked tuft back",
        "button tack back",
        "studded-back buttons",
        "button tufted back",
        "button tacked upholstery",
        "button-and-tack back",
        "button-studded tuft",
        "back studded with buttons",
        "button tack finish",
        "button-tack detail",
        "pin-back tufting",
        "button-back studs",
        "tack & button back",
        "button-studded upholstery"
    ],
    spelling_variations: [
        "buttontackedback",
        "button-tacked-back",
        "button tackedback",
        "button tacked back ",
        "button­tacked back",
        "button tackedback",
        "button tacked-back",
        "buton tacked back",
        "buttontacked back",
        "button tackedback ",
        "button­tackedback",
        "buttontacked­back",
        "button tacked-back ",
        "button tackd back",
        "button-taced back"
    ]
},
{
      feature: "Open Back",
    synonyms: [
        "backless",
        "exposed back",
        "cutaway back",
        "open-backed",
        "back opening",
        "no-back design",
        "rear open frame",
        "back cutout",
        "back gap",
        "back aperture",
        "open rear rest",
        "back void",
        "back notch",
        "back clearance",
        "back recess",
        "open-backrest",
        "rear opening back",
        "back frame only",
        "back skeleton",
        "back lattice",
        "open rear support",
        "back slats open",
        "back frame exposed",
        "open-back frame",
        "back cut-away"
    ],
    spelling_variations: [
        "openback",
        "open-back ",
        "open back ",
        "openback ",
        "open-backrest",
        "open backrest",
        "open­back",
        "open-backrest ",
        "openbackrest",
        "open-back rest",
        "openback rest",
        "openback-rest",
        "open-backrest",
        "open back-rest",
        "openback-rest"
    ]
},
{
      feature: "Arched Back",
    synonyms: [
        "curved backrest",
        "arched-profile back",
        "bowed back",
        "arc back",
        "arched silhouette",
        "arched-frame back",
        "arch-backed",
        "archback",
        "arched contour",
        "arched shell back",
        "arched-support back",
        "arched-form back",
        "arched-top back",
        "arched panel back",
        "arched cushion back",
        "arched wooden back",
        "arched metal back",
        "arched upholstered back",
        "arched-lattice back",
        "arched-beam back",
        "arched-rib back",
        "arched slat back",
        "arched-grid back",
        "arched lattice back",
        "arched trim back"
    ],
    spelling_variations: [
        "archedback",
        "arched-back ",
        "arched back ",
        "arched backrest",
        "archedbackrest",
        "arched-backrest",
        "arched back-rest",
        "arched-back rest",
        "archedback-rest",
        "arched–back",
        "archedback ",
        "arched-backrest ",
        "archedb ack",
        "archd back",
        "arced back"
    ]
},
{
      feature: "VerticalQuiltPattern",
    synonyms: [
        "vertical quilting",
        "channel tufting",
        "vertical tuft pattern",
        "vertical stitched channels",
        "row quilting",
        "ribbon tufting",
        "striped quilting",
        "bar quilting",
        "vertical pleating",
        "rail quilting",
        "linear tufting",
        "banded tufting",
        "pipe tufting",
        "vertical-channels back",
        "vertical quilt lines",
        "column tufting",
        "vertical seam quilting",
        "tube quilting",
        "vertical paneled tuft",
        "rail-style tuft",
        "pillar tufting",
        "vector quilt lines",
        "vertical panel quilt",
        "vertical grid quilting",
        "vertical back channels"
    ],
    spelling_variations: [
        "verticalquiltpattern",
        "vertical-quiltpattern",
        "vertical quiltpattern",
        "vertical quilt pattern ",
        "verticalquilt pattern",
        "vertical-quilt pattern",
        "vertical quilts pattern",
        "vertical quilt-pattern",
        "vertical quilt pattern",
        "verticalquiltpattern ",
        "vertical­quiltpattern",
        "vertical quiltpattern ",
        "vertical­quilt pattern",
        "vertical-quiltpattern ",
        "vertical quilt–pattern"
    ]
},
{
      feature: "ExternalBackQuilted",
    synonyms: [
        "externally quilted back",
        "quilted exterior back",
        "outside quilt back",
        "outer quilted backrest",
        "back exterior quilting",
        "external quilting back",
        "back exterior quilt",
        "quilted-back outside",
        "back quilt exterior",
        "exterior quilt back",
        "external tufted back",
        "outer tufting back",
        "outside tufted back",
        "outer panel quilt back",
        "external paneled quilt back",
        "external grid quilt back",
        "external diamond quilt back",
        "external channel quilt back",
        "external box tuft back",
        "external stitch quilt back",
        "external quilt pattern back",
        "external seam quilt back",
        "external rail quilt back",
        "external vertical quilt back",
        "external horizontal quilt back"
    ],
    spelling_variations: [
        "externalbackquilted",
        "external-back-quilted",
        "external backquilted",
        "externalback-quilted",
        "external back quilted ",
        "external-backquilted",
        "external back-quilted",
        "externalback quilted",
        "externalbackquilted ",
        "external-back quilted",
        "externalback-quilted ",
        "external–back quilted",
        "externalback–quilted",
        "externallbackquilted",
        "external back-quilted"
    ]
},
{
      feature: "WithMovableHeadrest",
    synonyms: [
        "with adjustable headrest",
        "movable head support",
        "detachable headrest",
        "headrest included",
        "with pivot headrest",
        "with tilting headrest",
        "with swiveling headrest",
        "headrest attachment",
        "with flip-up headrest",
        "with extendable headrest",
        "with modular headrest",
        "with removable headrest",
        "with sliding headrest",
        "with movable pillow rest",
        "with headrest functionality",
        "with headrest option",
        "with headrest module",
        "with articulated headrest",
        "with jointed headrest",
        "with flex headrest",
        "with adjustable neck rest",
        "with head support rest",
        "with repositionable headrest",
        "headrest flexibility",
        "with movable head cushion"
    ],
    spelling_variations: [
        "withmovableheadrest",
        "with-movable-headrest",
        "with movable headrest ",
        "withmovable headrest",
        "with movable-headrest",
        "withmovable-headrest",
        "with movable headrest",
        "withmovableheadrest ",
        "withmovable-headrest ",
        "with movableheadrest",
        "with movablehead rest",
        "with movble headrest",
        "with moveable headrest",
        "withmovable head rest",
        "with-movable headrest"
    ]
}
]