export const productTypes = [
    {
      type: "Sofa",
      spelling_variations: [
        "sofa", "soffas", "sofa ", "soffas ", "sofa's", "sofa's ","sf",
        "sofa'ss", "sofa'ss ", "soffas'", "soffas' ", "sofa's'",
        "sofa's' ", "soffas's", "soffas's ", "sofa's'ss", "sofa's'ss ",
        "soffas'ss", "soffas'ss ", "sofa'ss'", "sofa'ss' ", "soffas'ss'",
        "soffas'ss' ", "sofa'sss", "sofa'sss ", "soffas'sss", "soffas'sss ",
        "sofa'ssss", "sofa'ssss ", "soffas'ssss", "soffas'ssss ", "sofa'sssss",
        "sofa'sssss ", "soffas'sssss", "soffas'sssss ", "sofa'ssssss",
        "sofa'ssssss ", "soffas'ssssss", "soffas'ssssss ", "sofa'sssssss",
        "sofa'sssssss ", "soffas'sssssss", "soffas'sssssss ", "sofa'ssssssss",
        "sofa'ssssssss ", "soffas'ssssssss", "soffas'ssssssss ", "sofa'sssssssss"
      ],
      synonyms: [
        "couch",
        "loveseat",
        "settee",
        "divan",
        "davenport",
        "chesterfield",
        "sectional",
        "fainting couch"
      ]
    },
    {
      type: "Armchair",
      spelling_variations: [
        "armchair", "armchairs", "armchair ", "armchairs ", "armchair's",
        "armchair's ", "armchair'ss", "armchair'ss ", "armchairs'",
        "armchairs' ", "armchair's'", "armchair's' ", "armchairs's",
        "armchairs's ", "armchair's'ss", "armchair's'ss ", "armchairs'ss",
        "armchairs'ss ", "armchair'ss'", "armchair'ss' ", "armchairs'ss'",
        "armchairs'ss' ", "armchair'sss", "armchair'sss ", "armchairs'sss",
        "armchairs'sss ", "armchair'ssss", "armchair'ssss ", "armchairs'ssss",
        "armchairs'ssss ", "armchair'sssss", "armchair'sssss ", "armchairs'sssss",
        "armchairs'sssss ", "armchair'ssssss", "armchair'ssssss ",
        "armchairs'ssssss", "armchairs'ssssss ", "armchair'sssssss",
        "armchair'sssssss ", "armchairs'sssssss", "armchairs'sssssss ",
        "armchair'ssssssss", "armchair'ssssssss ", "armchairs'ssssssss",
        "armchairs'ssssssss ", "armchair'sssssssss", "armchair'sssssssss ",
        "armchairs'sssssssss", "armchairs'sssssssss ", "armchair'ssssssssss",
        "armchair'ssssssssss ", "armchairs'ssssssssss", "armchairs'ssssssssss "
      ],
      synonyms: [
        "chair",
        "easy chair",
        "wing chair",
        "recliner",
        "club chair",
        "tub chair",
        "slipper chair"
      ]
    },
    {
      type: "Ottoman",
      spelling_variations: [
        "ottoman",
        "ottomans",
        "ottoman ",
        "ottoman's",
        "ottoman chair",
        "ottomann",
        "otoman",
        "ottomon",
        "ottomaan",
        "ottaman",
        "ottomam",
        "ottomah",
        "ottiman",
        "ottomna",
        "ottmaon",
        "ootoman",
        "footstool",
        "foot stool",
        "ottoman-",
        "ottomab"
      ],
      synonyms: [
        "footstool",
        "pouf",
        "pouffe",
        "storage ottoman",
        "ottoman bench",
        "cocktail ottoman",
        "footrest",
        "ottoman seat",
        "low stool",
        "living room stool",
        "sofa stool",
        "cube ottoman",
        "padded stool",
        "floor cushion",
        "upholstered stool",
        "ottoman table",
        "coffee table ottoman",
        "shoe bench",
        "lounge ottoman",
        "round ottoman",
        "square ottoman",
        "rectangle ottoman",
        "decorative stool",
        "multi-purpose stool",
        "accent stool"
      ]
    },
    {
      type: "Chaise Lounge",
      spelling_variations: [
        "chaise lounge",
        "chaise longue",
        "chaise-lounge",
        "chise lounge",
        "chase lounge",
        "shays lounge",
        "chaise",
        "chaise lounges",
        "chaise loung",
        "chaise lunge",
        "chaise long",
        "cheis lounge",
        "chaisse lounge",
        "chaiz lounge",
        "chaz lounge",
        "chaize lounge",
        "shayz lounge",
        "chaise loungue",
        "chaise loungr",
        "chaise loungw",
        "chaise loungh",
        "chas lounge",
        "chaise loungs",
        "chaise loungss",
        "chaise loinge",
        "chaise looung",
        "chaisse loung"
      ],
      synonyms: [
        "lounge chair",
        "reclining chair",
        "fainting couch",
        "daybed",
        "sunbed",
        "deck chair",
        "divan",
        "sofa lounger",
        "recliner lounge",
        "chaise sofa",
        "outdoor lounger",
        "indoor lounger",
        "patio lounger",
        "beach lounger",
        "long chair",
        "modern lounger",
        "lazy lounger",
        "comfort lounger",
        "curved lounge",
        "adjustable lounger",
        "studio lounger",
        "relaxation bed",
        "stretch chair",
        "oversized lounger",
        "media lounger"
      ]
    },
    {
      type: "Lounge Chair",
      spelling_variations: [
        "lounge chair", "lounging chair", "lounge chairs", "lounger", 
        "lounger chair", "lounge-chair", "loungechair", "lounge chair ",
        "loungchair", "lounge chari", "loune chair", "louge chair", 
        "lounch chair", "lounnge chair", "loungerchair", "loungechaur", 
        "lounfe chair", "lounge chaor", "lounge chai", "loungehair", 
        "loungecahir"
      ],
      synonyms: [
        "lounger",
        "accent chair",
        "reading chair",
        "indoor recliner",
        "poolside chair",
        "deck chair",
        "relaxing chair",
        "easy chair",
        "leisure chair",
        "balcony chair",
        "patio chair",
        "low recliner",
        "casual chair",
        "modern recliner",
        "comfort chair",
        "TV chair",
        "plush chair",
        "living room chair",
        "den chair",
        "arm-less recliner",
        "slanted chair",
        "sofa recliner",
        "lounge seat",
        "lazy chair",
        "sunroom chair"
      ]
    }    
  ];
  